
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "mod"
  name = "coloredslime"
  description = "Dye your slime blocks!"
  version = "1.2.6"
  platform = "fabric"
  license = "MIT"

# These are global requirements
[requirements]
  minecraft = "~1.17"
  fabric = "~0.11.3"

[dependencies]
  fabric = "*"

[dev]
  buildCommand = "./gradlew build"
