manifestVersion = 0

[package]
  type = "mod"
  name = "coloredslime"
  description = "Dye your slime blocks!"
  version = "1.1.4"
  platform = "fabric"
  license = "MIT"

[requirements]
  minecraft = "1.16.5"
  fabric = "0.11.3"

[dependencies]
  fabric = "*"

[dev]
  buildCommand = "./gradlew build"
