manifestVersion = 0

[package]
  type = "mod"
  name = "coloredslime"
  description = "Dye your slime blocks!"
  version = "1.1.2"
  platform = "fabric"
  license = "GPLv3"

[requirements]
  minecraft = ">=1.16.2"
  fabric = ">=0.7.4"

[dependencies]
  fabric = "*"

[dev]
  buildCommand = "./gradlew build"
