manifestVersion = 0

[package]
  type = "mod"
  name = "coloredslime"
  description = "Dye your slime blocks!"
  version = "1.2.3"
  platform = "fabric"
  license = "MIT"

[requirements]
  minecraft = "~1.17"

[dependencies]
  fabric = "*"

[dev]
  buildCommand = "./gradlew build"
